services:
  - type: web
    name: decentralized-social-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PINATA_API_KEY
        sync: false
      - key: PINATA_SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 5000
